### ISSUE TITLE
It should be possible to change the default keyboard shortcuts of MEP

### ISSUE THREAD

**Issue by GavriYashar** [GavriYashar/Matlab-Editor-Plugin#10]
it should be possible to change Keyboard shortcuts of MEP via PrefsPanel or at least via the settings file

 - [x] File Structure
 - [x] copy selected text (inserts in clipboard stack)
 - [x] clipboard stack
 - [x] duplicate lines
 - [x] delete lines
 - [x] live template viewer
 - [x] execute current lines
 - [x] bookmark viewer
 - [x] recently closed
 - [x] toggle bookmark

**Comment by michaelkonecny** [comment]
Would also be handy for duplicate line and delete current line.
