### ISSUE TITLE
Live Templates not working 

### ISSUE THREAD

**Issue by ppatel26** [GavriYashar/Matlab-Editor-Plugin#133]
```
Live Templates has been disabled for one or both following reasons:
  * No Replacement folder found in "/Users/parvpatel/Documents/MATLAB
  * No Variables folder found in "/Users/parvpatel/Documents/MATLAB"
please set "path.mepr.rep" and "path.mepr.var" manually
```

Above shows up after starting matlab. 

I tried to add the following lines in "startup.m" but that didnt solve it. 

```
at.mep.prefs.Settings.setProperty("path.mepr.rep", "/Users/parvpatel/Documents/MATLAB/MEP/Replacements");
at.mep.prefs.Settings.setProperty("path.mepr.var", "/Users/parvpatel/Documents/MATLAB/MEP/Replacements/Variables");
```

**Comment by GavriYashar** [comment]
You have to use the fully qualified paths
https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Live-Templates#setup

> If the startup doesn't add the pathes to the properties you have to set path.mepr.var=D\:\\<INSTALLDIR>\Replacements\\Variables and path.mepr.rep=D\:\\<INSTALLDIR>\\Replacements

**Comment by ppatel26** [comment]
It works. Thank you :)
