### ISSUE TITLE
Manual installation wiki not correct

### ISSUE THREAD

**Issue by michaelkonecny** [GavriYashar/Matlab-Editor-Plugin#155]
In Setup -> [Manual installation in the wiki](https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Setup#manual-installation), you advise people to copy the jar files into `C:\Programme\Matlab\MEP\` which most people will probably understand as `C:\Program Files\...`.
Later you say to copy `DefaultProps.properties` and `CustomProps.properties` to the same folder.
However, at least CustomProps has to be user-writable (without administrator privileges), otherwise MEP throws an error on startup.

It might be better to tell people to copy everything to a user-writable folder, e.g. `%appdata%\MathWorks\MATLAB\R2020b\MEP\`, or at least tell them specifically to put CustomProps to a different (user-writable folder).

I would have created a pull-request for this, but apparently there isn't a way of doing that for a project's Wiki, so I had to "spam" you this way.

Thank you, enjoy the holidays!

**Comment by GavriYashar** [comment]
Thank you for pointing it out. I updated the wiki accordingly.
