### ISSUE TITLE
FileStructure Viewer should also show inherited methods

### ISSUE THREAD

**Issue by MartinLechner-TD** [GavriYashar/Matlab-Editor-Plugin#34]
It would be a very nice feature if a class inherits some methods from parent classes that like in Eclipse a second press of Strg+F12 will also show all inherited methods with the class name of the implementing class in braces left to the method name.
In Matlab is it very difficult to find the implementation class of a method, so this would be a great improvement object orientated programming in Matlab.

**Comment by GavriYashar** [comment]
834d620e93665b56f1ef93971c4c7ad4293721b9

**Comment by GavriYashar** [comment]
closed V1.18
