### ISSUE TITLE
FileStructure Viewer: Behavior when pressing Enter

### ISSUE THREAD

**Issue by MartinLechner-TD** [GavriYashar/Matlab-Editor-Plugin#37]
Pressing <kbd>Enter</kbd> in the search box should jump to the first marked hit of the search results.
In Eclipse opening the similar panel (<kbd>Strg</kbd>+<kbd>o</kbd>) marks the method of the actual cursor selection. The search narrows the possible hits and always the first element is selected, so it's always clear for the user to which method will be jumped after pressing <kbd>Enter</kbd>. Pressing <kbd>Esc</kbd> will always close the FileStructure Viewer without modifying the actual cursor position.

**Comment by GavriYashar** [comment]
> Pressing <kbd>Esc</kbd> will always close the FileStructure Viewer without modifying the actual cursor position.
is there a problem with this? Esc always closes a JFrame (from MEP) w/o modifying anything. at least it should
