### ISSUE TITLE
FileStructure Viewer (Classes) should show the properties and their Setter and Getter Methods

### ISSUE THREAD

**Issue by MartinLechner-TD** [GavriYashar/Matlab-Editor-Plugin#41]
The file structure viewer shows only methods of a class. This view should be extended to show also the properties and their getter and setter methods.
The information is provided in the meta class of Matlab:
- [x] use `PropertyList.Name` to show all properties,
- [x] use `PropertyList.GetMethod` to show all defined getter methods
- [x] use `PropertyList.SetMethod` to show all defined setter methods

**Comment by GavriYashar** [comment]
Using `PropertyList.GetMethod` `PropertyList.SetMethod` is not what i need in the code, unless i get a `com.mathworks.widgets.text.mcode.MTree.Node` returned somehow

**Comment by GavriYashar** [comment]
*sigh*
3f54a07fc9a2d2611d4e98de4e758f7ee41803e0
8d884f679043dde7113636e86211ef1fdd54f199
fadf462cd8d6a6e94a593e6c9e07a51fb7287ea7
aff7f12d162a4720f869fbc04296c5a12d108ea2
597b538cacaea4a73bb96d81fbd56d4522ab093c
f4364fb9b4fce9413d3062bdf52c154d62ad516a
0e9f4e0899ed68f8cd0ea2552ce555a55b67f7e1

**Comment by GavriYashar** [comment]
*sigh*
3f54a07fc9a2d2611d4e98de4e758f7ee41803e0
8d884f679043dde7113636e86211ef1fdd54f199
fadf462cd8d6a6e94a593e6c9e07a51fb7287ea7
aff7f12d162a4720f869fbc04296c5a12d108ea2
597b538cacaea4a73bb96d81fbd56d4522ab093c
f4364fb9b4fce9413d3062bdf52c154d62ad516a
0e9f4e0899ed68f8cd0ea2552ce555a55b67f7e1

*closed*
