### ISSUE TITLE
MEP wont get started by startup.m

### ISSUE THREAD

**Issue by michaelkonecny** [GavriYashar/Matlab-Editor-Plugin#51]
Loading MEP via the command line works fine.

However, if i try to put
`    at.justin.matlab.Start.start('<path>/CustomProps.properties', ...
                                 '<path>/DefaultProps.properties');`
in startup.m, Matlab won't start, in fact it won't even get past the splash screen.

Any ideas on what to do?

I'm using Matlab R2016b and MEP 1.07.

**Comment by GavriYashar** [comment]
* You have the *.properties files in the given location?
* are the paths correctly written in *.properties file? see [Workarounds](https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Workarounds)
* your javaclasspath.txt is correct? see [manual installation](https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Setup#manual-installation)

**Comment by michaelkonecny** [comment]
I set 
`feature.enableReplacements = false`
because I don't need it so I didn't set any value to `path.mepr.rep` and `path.mepr.var`.
Is that OK?

javaclasspath.txt is correct, the classes get correctly loaded and I can use them, just not via the startup.m

I will look for the log file.

**Comment by michaelkonecny** [comment]
Sorry, I can't find any usable .log file. I tried launching matlab using `matlab --logfile "c:\mylogfile.log"`, but that doesn't seem to do anything.

I've also set some real paths to `path.mepr.rep` and `path.mepr.var`, (even though `feature.enableReplacements` is `false`), but that didn't change anything.

My instinct would be to think startup.m gets executed before the classes get fully loaded, which might create some mess.

Do you have any ideas?

**Comment by GavriYashar** [comment]
Could you turn off all features and turn them on one by another, restarting matlab in between?

**Comment by michaelkonecny** [comment]
Even with all features turned off, Matlab won't start.

**Comment by michaelkonecny** [comment]
Ha, I think I might have a clue:

I tried starting matlab with `javaclasspath.txt` empty and this content of `startup.m`:
`javaaddpath('c:\Users\user\Documents\MATLAB\MatlabEditorPlugin\matconsolectl-4.4.3.jar');
javaaddpath('c:\Users\user\Documents\MATLAB\MatlabEditorPlugin\MEP_1.07.jar');

pause(10);

at.justin.matlab.Start.start('c:\Users\user\Documents\MATLAB\MatlabEditorPlugin\CustomProps.properties', ...
                     'c:\Users\user\Documents\MATLAB\MatlabEditorPlugin\CustomProps.properties');`

MEP somehow did start, but I got this error in the console:
`java.lang.IllegalAccessError: tried to access method com.mathworks.mlwidgets.prefs.PrefsDialog.getMLPrefsDialog()Lcom/mathworks/mlservices/MLPrefsDialog; from class com.mathworks.mlwidgets.prefs.PrefsChanger
	at com.mathworks.mlwidgets.prefs.PrefsChanger.addPrefs(PrefsChanger.java:13)
	at at.justin.matlab.Start.addPrefs(Start.java:99)
	at at.justin.matlab.Start.start(Start.java:24)`.

**Comment by GavriYashar** [comment]
8cd457a3998cc4e83febdf728ac9144bda3712e2 may resolve this problem (i forgot to upload this version 1.08)

**Comment by michaelkonecny** [comment]
Now I get this error on startup: (splash screen is still open)

![error](https://cloud.githubusercontent.com/assets/4976024/23376407/41d9ed80-fd2c-11e6-9343-a5c1f06da2a3.PNG)

**Comment by GavriYashar** [comment]
Is the error statement here even remotely true? Do you have any .M file open in MATLAB?

**Comment by michaelkonecny** [comment]
Well, yes, because this thing appears when starting matlab, i.e. when the splash screen is still visible - before the main matlab window gets opened, so I suppose no Editor or CommandWindow instance has been created at that moment.

**Comment by GavriYashar** [comment]
It works for me and my colleagues. So there must be something different on your system. I just don't know what, or why. 

What happens if you press ok? Does matlab start or does matlab stay on the splash screen?

**Comment by michaelkonecny** [comment]
Lemme try...

**Comment by michaelkonecny** [comment]
It stays on the splash screen.

**Comment by GavriYashar** [comment]
Argh.... 

Okay. Thanks, I'll look into it tomorrow. Sorry for the inconvenience.

**Comment by michaelkonecny** [comment]
No probs, thanks for caring ;)

**Comment by GavriYashar** [comment]
i think i reproduced the error. it might be that we were lucky because we don't start MEP untill the very end of startup, this i think buys us enough time to start properly

**Comment by GavriYashar** [comment]
could you try this *.jar
[MEP_1.10.jar.zip](https://github.com/GavriYashar/Matlab-Editor-Plugin/files/810877/MEP_1.10.jar.zip)

**Comment by GavriYashar** [comment]
i think i may have fixed it, could you try this *jar
[MEP_1.10.jar.zip](https://github.com/GavriYashar/Matlab-Editor-Plugin/files/812929/MEP_1.10.jar.zip)

**Comment by michaelkonecny** [comment]
Yes! 🤝 
That works.

**Comment by GavriYashar** [comment]
good!

Thank you for reporting the bug and for your patience.
