### ISSUE TITLE
remember history of navigation between files and go back/forth using mouse back/forward buttons

### ISSUE THREAD

**Issue by michaelkonecny** [GavriYashar/Matlab-Editor-Plugin#63]
Feature suggestion.

It would be great to be able to remember the way I navigate through the code for example by using the Open <function> commant (Ctrl + D by default) or just switching between files in the editor.

This history could be kept in some array.

One could then go back in this history using the back/forward button on the mouse, or some keyboard shortcut, just like it is common in other IDEs.

Of course this idea needs to be a bit refined before implementation.

**Comment by michaelkonecny** [comment]
Wow, awesome!

**Comment by GavriYashar** [comment]
Thank you!
