### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Esmaeili-Najafabadi** [GavriYashar/Matlab-Editor-Plugin#80]
I'm Using Matlab 2016a. after following the installation guides and restarting I get following error.
That would be great if someone helps me with this issue. 
``` Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
MATLAB:UndefinedFunction
Undefined function 'This' for input arguments of type 'char'.
```

> In matlabrc (line 212)

**Comment by GavriYashar** [comment]
somewhere in your `startup.m` is a variable/function named `This` called that is neither defined nor in Matlabs search path. Make sure in startup is only what you need/want.
